// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/surp.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetadataKey int32

const (
	MetadataKey_METADATA_KEY_UNSPECIFIED MetadataKey = 0
	MetadataKey_META_RO                  MetadataKey = 1
	MetadataKey_META_MIN                 MetadataKey = 2
	MetadataKey_META_MAX                 MetadataKey = 3
	MetadataKey_META_UNIT                MetadataKey = 4
	MetadataKey_META_DESCRIPTION         MetadataKey = 5
)

// Enum value maps for MetadataKey.
var (
	MetadataKey_name = map[int32]string{
		0: "METADATA_KEY_UNSPECIFIED",
		1: "META_RO",
		2: "META_MIN",
		3: "META_MAX",
		4: "META_UNIT",
		5: "META_DESCRIPTION",
	}
	MetadataKey_value = map[string]int32{
		"METADATA_KEY_UNSPECIFIED": 0,
		"META_RO":                  1,
		"META_MIN":                 2,
		"META_MAX":                 3,
		"META_UNIT":                4,
		"META_DESCRIPTION":         5,
	}
)

func (x MetadataKey) Enum() *MetadataKey {
	p := new(MetadataKey)
	*p = x
	return p
}

func (x MetadataKey) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetadataKey) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_surp_proto_enumTypes[0].Descriptor()
}

func (MetadataKey) Type() protoreflect.EnumType {
	return &file_proto_surp_proto_enumTypes[0]
}

func (x MetadataKey) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetadataKey.Descriptor instead.
func (MetadataKey) EnumDescriptor() ([]byte, []int) {
	return file_proto_surp_proto_rawDescGZIP(), []int{0}
}

type Value struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*Value_BoolValue
	//	*Value_U64Value
	//	*Value_S64Value
	//	*Value_F64Value
	//	*Value_StrValue
	Value         isValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_proto_surp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_proto_surp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_proto_surp_proto_rawDescGZIP(), []int{0}
}

func (x *Value) GetValue() isValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Value) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*Value_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *Value) GetU64Value() uint64 {
	if x != nil {
		if x, ok := x.Value.(*Value_U64Value); ok {
			return x.U64Value
		}
	}
	return 0
}

func (x *Value) GetS64Value() int64 {
	if x != nil {
		if x, ok := x.Value.(*Value_S64Value); ok {
			return x.S64Value
		}
	}
	return 0
}

func (x *Value) GetF64Value() float64 {
	if x != nil {
		if x, ok := x.Value.(*Value_F64Value); ok {
			return x.F64Value
		}
	}
	return 0
}

func (x *Value) GetStrValue() string {
	if x != nil {
		if x, ok := x.Value.(*Value_StrValue); ok {
			return x.StrValue
		}
	}
	return ""
}

type isValue_Value interface {
	isValue_Value()
}

type Value_BoolValue struct {
	BoolValue bool `protobuf:"varint,1,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type Value_U64Value struct {
	U64Value uint64 `protobuf:"varint,2,opt,name=u64_value,json=u64Value,proto3,oneof"`
}

type Value_S64Value struct {
	S64Value int64 `protobuf:"varint,3,opt,name=s64_value,json=s64Value,proto3,oneof"`
}

type Value_F64Value struct {
	F64Value float64 `protobuf:"fixed64,4,opt,name=f64_value,json=f64Value,proto3,oneof"`
}

type Value_StrValue struct {
	StrValue string `protobuf:"bytes,5,opt,name=str_value,json=strValue,proto3,oneof"`
}

func (*Value_BoolValue) isValue_Value() {}

func (*Value_U64Value) isValue_Value() {}

func (*Value_S64Value) isValue_Value() {}

func (*Value_F64Value) isValue_Value() {}

func (*Value_StrValue) isValue_Value() {}

type MetadataEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           MetadataKey            `protobuf:"varint,1,opt,name=key,proto3,enum=surp.MetadataKey" json:"key,omitempty"`
	Value         *Value                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataEntry) Reset() {
	*x = MetadataEntry{}
	mi := &file_proto_surp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataEntry) ProtoMessage() {}

func (x *MetadataEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_surp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataEntry.ProtoReflect.Descriptor instead.
func (*MetadataEntry) Descriptor() ([]byte, []int) {
	return file_proto_surp_proto_rawDescGZIP(), []int{1}
}

func (x *MetadataEntry) GetKey() MetadataKey {
	if x != nil {
		return x.Key
	}
	return MetadataKey_METADATA_KEY_UNSPECIFIED
}

func (x *MetadataEntry) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

type MessageIS struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ttl           uint32                 `protobuf:"varint,1,opt,name=ttl,proto3" json:"ttl,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value         *Value                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Metadata      []*MetadataEntry       `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageIS) Reset() {
	*x = MessageIS{}
	mi := &file_proto_surp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageIS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageIS) ProtoMessage() {}

func (x *MessageIS) ProtoReflect() protoreflect.Message {
	mi := &file_proto_surp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageIS.ProtoReflect.Descriptor instead.
func (*MessageIS) Descriptor() ([]byte, []int) {
	return file_proto_surp_proto_rawDescGZIP(), []int{2}
}

func (x *MessageIS) GetTtl() uint32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *MessageIS) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MessageIS) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *MessageIS) GetMetadata() []*MetadataEntry {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type MessageSET struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         *Value                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageSET) Reset() {
	*x = MessageSET{}
	mi := &file_proto_surp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageSET) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageSET) ProtoMessage() {}

func (x *MessageSET) ProtoReflect() protoreflect.Message {
	mi := &file_proto_surp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageSET.ProtoReflect.Descriptor instead.
func (*MessageSET) Descriptor() ([]byte, []int) {
	return file_proto_surp_proto_rawDescGZIP(), []int{3}
}

func (x *MessageSET) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MessageSET) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

type MessageGET struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ttl           uint32                 `protobuf:"varint,1,opt,name=ttl,proto3" json:"ttl,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageGET) Reset() {
	*x = MessageGET{}
	mi := &file_proto_surp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageGET) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageGET) ProtoMessage() {}

func (x *MessageGET) ProtoReflect() protoreflect.Message {
	mi := &file_proto_surp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageGET.ProtoReflect.Descriptor instead.
func (*MessageGET) Descriptor() ([]byte, []int) {
	return file_proto_surp_proto_rawDescGZIP(), []int{4}
}

func (x *MessageGET) GetTtl() uint32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *MessageGET) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SurpMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*SurpMessage_Is
	//	*SurpMessage_Set
	//	*SurpMessage_Get
	Msg           isSurpMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SurpMessage) Reset() {
	*x = SurpMessage{}
	mi := &file_proto_surp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SurpMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SurpMessage) ProtoMessage() {}

func (x *SurpMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_surp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SurpMessage.ProtoReflect.Descriptor instead.
func (*SurpMessage) Descriptor() ([]byte, []int) {
	return file_proto_surp_proto_rawDescGZIP(), []int{5}
}

func (x *SurpMessage) GetMsg() isSurpMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *SurpMessage) GetIs() *MessageIS {
	if x != nil {
		if x, ok := x.Msg.(*SurpMessage_Is); ok {
			return x.Is
		}
	}
	return nil
}

func (x *SurpMessage) GetSet() *MessageSET {
	if x != nil {
		if x, ok := x.Msg.(*SurpMessage_Set); ok {
			return x.Set
		}
	}
	return nil
}

func (x *SurpMessage) GetGet() *MessageGET {
	if x != nil {
		if x, ok := x.Msg.(*SurpMessage_Get); ok {
			return x.Get
		}
	}
	return nil
}

type isSurpMessage_Msg interface {
	isSurpMessage_Msg()
}

type SurpMessage_Is struct {
	Is *MessageIS `protobuf:"bytes,1,opt,name=is,proto3,oneof"`
}

type SurpMessage_Set struct {
	Set *MessageSET `protobuf:"bytes,2,opt,name=set,proto3,oneof"`
}

type SurpMessage_Get struct {
	Get *MessageGET `protobuf:"bytes,3,opt,name=get,proto3,oneof"`
}

func (*SurpMessage_Is) isSurpMessage_Msg() {}

func (*SurpMessage_Set) isSurpMessage_Msg() {}

func (*SurpMessage_Get) isSurpMessage_Msg() {}

var File_proto_surp_proto protoreflect.FileDescriptor

const file_proto_surp_proto_rawDesc = "" +
	"\n" +
	"\x10proto/surp.proto\x12\x04surp\"\xad\x01\n" +
	"\x05Value\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x01 \x01(\bH\x00R\tboolValue\x12\x1d\n" +
	"\tu64_value\x18\x02 \x01(\x04H\x00R\bu64Value\x12\x1d\n" +
	"\ts64_value\x18\x03 \x01(\x03H\x00R\bs64Value\x12\x1d\n" +
	"\tf64_value\x18\x04 \x01(\x01H\x00R\bf64Value\x12\x1d\n" +
	"\tstr_value\x18\x05 \x01(\tH\x00R\bstrValueB\a\n" +
	"\x05value\"W\n" +
	"\rMetadataEntry\x12#\n" +
	"\x03key\x18\x01 \x01(\x0e2\x11.surp.MetadataKeyR\x03key\x12!\n" +
	"\x05value\x18\x02 \x01(\v2\v.surp.ValueR\x05value\"\x85\x01\n" +
	"\tMessageIS\x12\x10\n" +
	"\x03ttl\x18\x01 \x01(\rR\x03ttl\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\x05value\x18\x03 \x01(\v2\v.surp.ValueR\x05value\x12/\n" +
	"\bmetadata\x18\x04 \x03(\v2\x13.surp.MetadataEntryR\bmetadata\"C\n" +
	"\n" +
	"MessageSET\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\x05value\x18\x02 \x01(\v2\v.surp.ValueR\x05value\"2\n" +
	"\n" +
	"MessageGET\x12\x10\n" +
	"\x03ttl\x18\x01 \x01(\rR\x03ttl\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x83\x01\n" +
	"\vSurpMessage\x12!\n" +
	"\x02is\x18\x01 \x01(\v2\x0f.surp.MessageISH\x00R\x02is\x12$\n" +
	"\x03set\x18\x02 \x01(\v2\x10.surp.MessageSETH\x00R\x03set\x12$\n" +
	"\x03get\x18\x03 \x01(\v2\x10.surp.MessageGETH\x00R\x03getB\x05\n" +
	"\x03msg*y\n" +
	"\vMetadataKey\x12\x1c\n" +
	"\x18METADATA_KEY_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aMETA_RO\x10\x01\x12\f\n" +
	"\bMETA_MIN\x10\x02\x12\f\n" +
	"\bMETA_MAX\x10\x03\x12\r\n" +
	"\tMETA_UNIT\x10\x04\x12\x14\n" +
	"\x10META_DESCRIPTION\x10\x05B\"Z github.com/burgrp/surp-go/pkg/pbb\x06proto3"

var (
	file_proto_surp_proto_rawDescOnce sync.Once
	file_proto_surp_proto_rawDescData []byte
)

func file_proto_surp_proto_rawDescGZIP() []byte {
	file_proto_surp_proto_rawDescOnce.Do(func() {
		file_proto_surp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_surp_proto_rawDesc), len(file_proto_surp_proto_rawDesc)))
	})
	return file_proto_surp_proto_rawDescData
}

var file_proto_surp_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_surp_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_surp_proto_goTypes = []any{
	(MetadataKey)(0),      // 0: surp.MetadataKey
	(*Value)(nil),         // 1: surp.Value
	(*MetadataEntry)(nil), // 2: surp.MetadataEntry
	(*MessageIS)(nil),     // 3: surp.MessageIS
	(*MessageSET)(nil),    // 4: surp.MessageSET
	(*MessageGET)(nil),    // 5: surp.MessageGET
	(*SurpMessage)(nil),   // 6: surp.SurpMessage
}
var file_proto_surp_proto_depIdxs = []int32{
	0, // 0: surp.MetadataEntry.key:type_name -> surp.MetadataKey
	1, // 1: surp.MetadataEntry.value:type_name -> surp.Value
	1, // 2: surp.MessageIS.value:type_name -> surp.Value
	2, // 3: surp.MessageIS.metadata:type_name -> surp.MetadataEntry
	1, // 4: surp.MessageSET.value:type_name -> surp.Value
	3, // 5: surp.SurpMessage.is:type_name -> surp.MessageIS
	4, // 6: surp.SurpMessage.set:type_name -> surp.MessageSET
	5, // 7: surp.SurpMessage.get:type_name -> surp.MessageGET
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_proto_surp_proto_init() }
func file_proto_surp_proto_init() {
	if File_proto_surp_proto != nil {
		return
	}
	file_proto_surp_proto_msgTypes[0].OneofWrappers = []any{
		(*Value_BoolValue)(nil),
		(*Value_U64Value)(nil),
		(*Value_S64Value)(nil),
		(*Value_F64Value)(nil),
		(*Value_StrValue)(nil),
	}
	file_proto_surp_proto_msgTypes[5].OneofWrappers = []any{
		(*SurpMessage_Is)(nil),
		(*SurpMessage_Set)(nil),
		(*SurpMessage_Get)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_surp_proto_rawDesc), len(file_proto_surp_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_surp_proto_goTypes,
		DependencyIndexes: file_proto_surp_proto_depIdxs,
		EnumInfos:         file_proto_surp_proto_enumTypes,
		MessageInfos:      file_proto_surp_proto_msgTypes,
	}.Build()
	File_proto_surp_proto = out.File
	file_proto_surp_proto_goTypes = nil
	file_proto_surp_proto_depIdxs = nil
}
